//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCExamShop.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Comment
    {
        public int CommentId { get; set; }
        [Required]
        [StringLength(32, MinimumLength = 1, ErrorMessage = "Author name must be between 1 and 32 characters!")]
        public string Author { get; set; }

        [Display(Name = "E-Mail Address")]
        [Required]
        [EmailAddress(ErrorMessage = "E-Mail Address does not appear to be valid!")]
        public string UserEmail { get; set; }

        [Display(Name = "Comment")]
        [StringLength(10, MinimumLength = 3000, ErrorMessage = "Comment must be between 10 and 3000 characters!")]
        public string UserComment { get; set; }

        [Display(Name = "Creation Date")]
        public System.DateTime CommentCreationDate { get; set; }

        [Display(Name = "Blog Id")]
        public int BlogId { get; set; }

        public virtual Blog Blog { get; set; }
    }
}
